### ISSUE TITLE
[META] OUI Theming & Path to Theme 1

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#212]
This issue is a draft/placeholder while OUI team works together on theming system requirements. There is a distinct difference between creating OUI theming capabilities and executing `Theme 1`. More details to come. 
Short term:
- [ ] Complete engineering research & approach spike https://github.com/opensearch-project/oui/issues/44
- [ ] Provide a list of themable UI items
- [ ] Identify component-level refactoring to match theming approach 

Mid Term:
- [ ] Allow user to set light/dark mode defaults based on system settings

Path to `Theme 1` throughout Q1 & Q2:
- [ ] Design exploration of `Theme 1` utilizing updated branding colors for light and dark mode
- [ ] End-to-end update of all themeable design assets 
- [ ] Replace current OUI base theme with `Theme 1`
- [ ] Build of `Theme 1`
- [ ] Version bump of OUI
- [ ] Campaign for OUI version bump adoption

**Comment by kavilla** [comment]
Update theme default values.

**Comment by KrooshalUX** [comment]
> Update theme default values.

This is "Replace current OUI Base theme with `Theme 1" in the to-do list @kavilla

**Comment by anirudha** [comment]
Closing — superseded by the V9 theme initiative (#1695) and OUI 2.0 work. The new theme system addresses the goals of this issue. See the V9 RFC for the current direction.
