### ISSUE TITLE
(Meta) OuiAccordionCard Component

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#574]
- [ ] Add component to Figma library
- [ ] Create OuiAccordionCard component : https://github.com/opensearch-project/oui/issues/944 
- [ ] Update OUI Docs website to add OuiAccordionCard as a Card variant
- [ ] Bump & release updated version of OUI

**Comment by anirudha** [comment]
Closing — this issue has been blocked for over a year with no progress on its blockers. If the blocking conditions are resolved in the future, this can be reopened or a new issue created with updated context.
