### ISSUE TITLE
[META] Changes to OUI & GitHub Docs (DRAFT)

### ISSUE THREAD

**Issue by KrooshalUX** [opensearch-project/oui#85]
**REQUIRED BEFORE PUBLIC LAUNCH**

- [ ] Remove all Elastic references from .md
- [ ] Remove all elastic references from all doc pages
- [ ] Remove Elastic charting pages
- [ ] Placeholder OUI Chart pages
- [ ] Remove NEW flag from Notification event

**OVER TIME**

**Comment by anirudha** [comment]
Closing — this documentation issue has been open since 2022/2023 with no progress. The doc site has been significantly updated since then. If specific documentation gaps remain, please open a new issue with current context.
